### ISSUE TITLE
Hide x-rgw-object-type header

### ISSUE THREAD

**Issue by mfrancis95** [ComputerScienceHouse/docker-s3-proxy#12]
https://assets.csh.rit.edu/csh-material-bootstrap/3.3.6/dist/csh-material-bootstrap.min.css returns this header in the response but I haven't seen other links return it. It appears to be related to Ceph.

@sgreene570 thoughts on the matter?

**Comment by sgreene570** [comment]
the rgw s3 api is not 100% so this could just be a bug / missed feature.

**Comment by mfrancis95** [comment]
It seems safe to hide. I was just curious because I haven't seen that header pop up anywhere else. The more headers I can remove from the responses, the better.
