### ISSUE TITLE
Use http1.1 or better

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/docker-s3-proxy#6]
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version

Ideally use http2, but at least 1.1 or 1.2

**Comment by mfrancis95** [comment]
Proxy version set here: 5c098006e1f718abbf2ba3b43b57385755a220cc.

Leaving this open because it's still not using HTTP/2 yet.

Might not be necessary to do HTTP/2 stuff through an nginx config if we can enable HTTP/2 from the OpenShift side of things.
